name: Model Retraining

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Workflow-CI/processed/cleaned_training.csv'
      - 'Workflow-CI/modelling.py'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Workflow-CI
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install MLflow and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas numpy
    
    - name: Start MLflow server
      run: |
        mlflow server --host 127.0.0.1 --port 5000 &
        sleep 5
    
    - name: Run MLflow project
      run: |
        mlflow run . \
          -P C=1.0 \
          -P max_iter=1000 \
          -P data_path=processed/cleaned_training.csv
      env:
        MLFLOW_TRACKING_URI: http://127.0.0.1:5000
    
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: Workflow-CI/mlruns/
